### ISSUE TITLE
error when starting it

### ISSUE THREAD

**Issue by stefanpinterBE** [mgnsk/sway-fader#2]
hi! 

i guess I have to add my ~/go/bin to PATH variable, but anyways, this is my error

/home/parallels/go/bin/sway-fader
error: command "[con_id=187651031411744] opacity 0.7125;" unsuccessful: Expected one of these tokens: <end>, '[', 'move', 'exec', 'exit', 'restart', 'reload', 'shmlog', 'debuglog', 'border', 'layout', 'append_layout', 'workspace', 'focus', 'kill', 'open', 'fullscreen', 'sticky', 'split', 'floating', 'mark', 'unmark', 'resize', 'rename', 'nop', 'scratchpad', 'swap', 'title_format', 'title_window_icon', 'mode', 'bar', 'gaps'error: command "[con_id=187651031558032] opacity 0.7125;" unsuccessful: Expected one of these tokens: <end>, '[', 'move', 'exec', 'exit', 'restart', 'reload', 'shmlog', 'debuglog', 'border', 'layout', 'append_layout', 'workspace', 'focus', 'kill', 'open', 'fullscreen', 'sticky', 'split', 'floating', 'mark', 'unmark', 'resize', 'rename', 'nop', 'scratchpad', 'swap', 'title_format', 'title_window_icon', 'mode', 'bar', 'gaps'error: command "[con_id=187651032242064] opacity 0.7125;" unsuccessful: Expected one of these tokens: <end>, '[', 'move', 'exec', 'exit', 'restart', 'reload', 'shmlog', 'debuglog', 'border', 'layout', 'appe....

running on Ubuntu 23.10 for ARM

**Comment by mgnsk** [comment]
It looks like i3 doesn't have the built-in `opacity` command since Xorg needs a separate compositor for these kinds of things to work. I recommend using Wayland + Sway. I'll remove i3 support since I'm only testing with sway.

**Comment by agenttank** [comment]
yeah, I also recommend Wayland and Sway ;)
i am not sure yet, if it works in my ubuntu ARM version in parallels (MacOs hypervisor)

thank you for your quick Response
